name: Sample java project

on:
  push:
    branches:
      - 'github-actions-slack-voxmedia'

jobs:

  docker:
    name: Build & Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:${GITHUB_SHA::8} .
      - name: Notify slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: bhushan-personal-testing
          status: STARTED
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      - name: Publish Docker image
        run: docker push $REPO:${GITHUB_SHA::8}
