name: Sample java project

on:
  push:
    branches:
      - 'github-action-slack'

jobs:

  docker:
    name: Build & Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO:${GITHUB_SHA::8}
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          config: .github/config/slack.yaml
        if: always()

